apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: student-feedback
  labels:
    app: admin-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
        tier: backend
    spec:
      containers:
      - name: admin-service
        image: kartikdumadiya/admin-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
          name: http
        env:
        - name: ADMIN_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: feedback-system-config
              key: ADMIN_SERVICE_PORT
        - name: STUDENT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: feedback-system-config
              key: STUDENT_SERVICE_URL
        - name: FEEDBACK_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: feedback-system-config
              key: FEEDBACK_SERVICE_URL
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: feedback-system-config
              key: NODE_ENV
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: student-feedback
  labels:
    app: admin-service
spec:
  type: ClusterIP
  selector:
    app: admin-service
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
    name: http