apiVersion: v1
kind: ConfigMap
metadata:
  name: feedback-system-config
  namespace: student-feedback
data:
  STUDENT_SERVICE_PORT: "3001"
  FEEDBACK_SERVICE_PORT: "3002"
  ADMIN_SERVICE_PORT: "3003"
  STUDENT_SERVICE_URL: "http://student-service:3001"
  FEEDBACK_SERVICE_URL: "http://feedback-service:3002"
  NODE_ENV: "production"