apiVersion: v1
kind: Secret
metadata:
  name: feedback-system-secret
  namespace: student-feedback
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://dbUser:V3Kf2mVSEd74hxlE@student-feedback-db.e3m8zqf.mongodb.net/?retryWrites=true&w=majority&appName=student-feedback-db"